packages:
  - templates/*
  - blocks/*
  - tools/*

configDependencies:
  '@pnpm/plugin-trusted-deps': 0.2.0+sha512-jqiCC8kyrwOERwMWPo2RB1YlDMMS5WsPSA8Uwi3EXAYwyOSNtqKhrB9bs543JGUiz4yaA9h6nE3q98fG14AEyQ==

sharedWorkspaceLockfile: false
